include_directories(${src_dir}/boost)
#message(${src_dir}/boost)
#link_directories(${PROJECT_BINARY_DIR}/boost/)
#include_directories(/usr/local/include)
#link_directories(/usr/local/lib/)
#link_libraries(libboost_thread-mt.a libboost_timer.a libboost_system.a)
